export const CONNECTION_CONNECTED = "CONNECTION_CONNECTED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";
export const LOGIN = "LOGIN";
export const LOGIN_RETURNED = "LOGIN_RETURNED";

export const DARKMODE_SWITCH = "DARKMODE_SWITCH";
export const DARKMODE_SWITCH_RETURN = "DARKMODE_SWITCH_RETURN";

export const GRAPH_TIMEFRAME_CHANGED = "GRAPH_TIMEFRAME_CHANGED";

//DB constants
export const DB_GET_USERDATA = "DB_GET_USERDATA";
export const DB_USERDATA_RETURNED = "DB_USERDATA_RETURNED";

export const DB_ADD_BLACKLIST = "DB_ADD_BLACKLIST";
export const DB_DEL_BLACKLIST = "DB_DEL_BLACKLIST";
export const DB_ADDDEL_BLACKLIST_RETURNED = "DB_ADDDEL_BLACKLIST_RETURNED";

export const DB_ADD_FAVORITE = "DB_ADD_FAVORITE";
export const DB_ADD_FAVORITE_RETURNED = "DB_ADD_FAVORITE_RETURNED";
export const DB_DEL_FAVORITE = "DB_DEL_FAVORITE";
export const DB_DEL_FAVORITE_RETURNED = "DB_DEL_FAVORITE_RETURNED";

export const DB_BLUECHIPS_CHECK = "DB_BLUECHIPS_CHECK";
export const DB_BLUECHIPS_CHECK_RETURNED = "DB_BLUECHIPS_CHECK_RETURNED";
export const DB_GET_BLUECHIPS = "DB_GET_BLUECHIPS";
export const DB_GET_BLUECHIPS_RETURNED = "DB_BLUECHIPS_RETURNED";
export const DB_GET_BLUECHIPS_USER = "DB_GET_BLUECHIPS_USER";
export const DB_GET_BLUECHIPS_USER_RETURNED = "DB_GET_BLUECHIPS_USER_RETURNED";
export const DB_ADD_BLUECHIPS_GURU = "DB_ADD_BLUECHIPS_GURU";
export const DB_ADD_BLUECHIPS_GURU_RETURNED = "DB_ADD_BLUECHIPS_GURU_RETURNED";
export const DB_DEL_BLUECHIPS_GURU = "DB_DEL_BLUECHIPS_GURU";
export const DB_DEL_BLUECHIPS_GURU_RETURNED = "DB_DEL_BLUECHIPS_GURU_RETURNED";
export const DB_ADD_BLUECHIPS = "DB_ADD_BLUECHIP";
export const DB_DEL_BLUECHIPS = "DB_DEL_BLUECHIP";
export const DB_ADD_BLUECHIPS_RETURNED = "DB_ADD_BLUECHIPS_RETURNED";
export const DB_DEL_BLUECHIPS_RETURNED = "DB_DEL_BLUECHIPS_RETURNED";

export const DB_ADD_WALLET = "DB_ADD_WALLET";
export const DB_ADD_WALLET_WATCHLIST = "DB_ADD_WALLET_WATCHLIST";
export const DB_ADD_WALLET_RETURNED = "DB_ADD_WALLET_RETURNED";
export const DB_DEL_WALLET = "DB_DEL_WALLET";
export const DB_DEL_WALLET_WATCHLIST = "DB_DEL_WALLET_WATCHLIST";

export const DB_DEL_WALLET_RETURNED = "DB_DEL_WALLET_RETURNED";
export const DB_UPDATE_WALLET = "DB_UPDATE_WALLET";
export const DB_UPDATE_WALLET_RETURNED = "DB_UPDATE_WALLET_RETURNED";
export const DB_UPDATE_WALLET_MOVEMENTS = "DB_UPDATE_WALLET_MOVEMENTS";
export const DB_UPDATE_WALLET_MOVEMENTS_RETURNED =
  "DB_UPDATE_WALLET_MOVEMENTS_RETURNED";
export const DB_UPDATE_ONE_MOV = "DB_UPDATE_ONE_MOV";
export const DB_UPDATE_ONE_MOV_RETURNED = "DB_UPDATE_ONE_MOV_RETURNED";
export const DB_UPDATE_WALLET_MOVEMENTS_PRICES =
  "DB_UPDATE_WALLET_MOVEMENTS_PRICES";
export const DB_UPDATE_WALLET_MOVEMENTS_PRICES_RETURNED =
  "DB_UPDATE_WALLET_MOVEMENTS_PRICES_RETURNED";
export const DB_GET_COIN_CATEGORIES = "DB_GET_COIN_CATEGORIES";
export const DB_GET_COIN_CATEGORIES_RETURNED =
  "DB_GET_COIN_CATEGORIES_RETURNED";
export const CHECK_ACCOUNT = "CHECK_ACCOUNT";
export const CHECK_ACCOUNT_RETURNED = "CHECK_ACCOUNT_RETURNED";

export const CONNECT_METAMASK = "CONNECT_METAMASK";
export const CONNECT_METAMASK_PASSIVE = "CONNECT_METAMASK_PASSIVE";
export const METAMASK_CONNECTED = "METAMASK_CONNECTED";
export const CONNECT_LEDGER = "CONNECT_LEDGER";

export const GET_CONTRACT_EVENTS = "GET_CONTRACT_EVENTS";
export const GET_CONTRACT_EVENTS_RETURNED = "GET_CONTRACT_EVENTS_RETURNED";

export const ERROR = "ERROR";

export const GET_MAX_EDITIONSIZE = "GET_MAX_EDITIONSIZE";
export const MAX_EDIT_SIZE_RETURNED = "MAX_EDIT_SIZE_RETURNED";
export const GET_CURRENTEDITION = "GET_CURRENTEDITION";
export const EDITION_RETURNED = "EDITION_RETURNED";
export const GET_USER_EDITIONS = "GET_USER_EDITIONS";
export const USER_EDITIONS_RETURNED = "USER_EDITIONS_RETURNED";
export const GET_USER_EDITIONS_DETAILS = "GET_USER_EDITIONS_DETAILS";
export const GET_ARTIST_EDITIONS = "GET_ARTIST_EDITIONS";
export const ARTIST_EDITIONS_RETURNED = "ARTIST_EDITIONS_RETURNED";
export const GET_ARTIST_EDITIONS_DETAILS = "GET_ARTIST_EDITIONS_DETAILS";
export const ARTIST_EDITIONS_DETAILS_RETURNED =
  "ARTIST_EDITIONS_DETAILS_RETURNED";
export const GET_EDITION_DETAILS = "GET_EDITION_DETAILS";
export const GET_EDITIONS_DETAILS = "GET_EDITIONS_DETAILS";
export const EDITION_DETAILS_RETURNED = "EDITION_DETAILS_RETURNED";
export const EDITIONS_DETAILS_RETURNED = "EDITION_DETAILS_RETURNED";

export const GET_TOKENJSON = "GET_TOKENJSON";
export const TOKENJSON_RETURNED = "TOKENJSON_RETURNED";

export const BUY_EDITION = "BUY_EDITION";
export const BUY_RETURNED = "BUY_RETURNED";
export const CREATE_NEW_EDITION = "CREATE_NEW_EDITION";
export const NEW_EDITION_RETURNED = "NEW_EDITION_RETURNED";
export const GIFT_EDITION = "GIFT_EDITION";
export const GIFT_EDITION_ARTIST = "GIFT_EDITION_ARTIST";
export const GIFT_EDITION_RETURNED = "GIFT_EDITION_RETURNED";

export const CHECK_GASPRICE = "CHECK_GASPRICE";
export const GASPRICE_RETURNED = "GASPRICE_RETURNED";

export const GET_AVAILABLE_ITEMS = "GET_AVAILABLE_ITEMS";
export const GET_ITEMS_CIRCULATING = "GET_ITEMS_CIRCULATING";
export const GET_SALES_VALUE = "GET_SALES_VALUE";
export const GET_ACCOUNT_ROLES = "GET_ACCOUNT_ROLES";
export const AVAILABLE_ITEMS_RETURNED = "AVAILABLE_ITEMS_RETURNED";
export const ITEMS_CIRCULATING_RETURNED = "ITEMS_CIRCULATING_RETURNED";
export const SALES_VALUE_RETURNED = "SALES_VALUE_RETURNED";
export const UPDATE_WAIT_COMPLETE = "UPDATE_WAIT_COMPLETE";
export const ACCOUNT_ROLES_RETURNED = "ACCOUNT_ROLES_RETURNED";
export const SET_ROLES = "SET_ROLES";
export const REVOKE_ROLES = "REVOKE_ROLES";

export const SET_ALLOWED_ARTIST = "SET_ALLOWED_ARTIST";
export const ALLOWED_ARTIST_RETURNED = "ALLOWED_ARTIST_RETURNED";
export const SET_OPEN_TO_ALL_ARTISTS = "SET_OPEN_TO_ALL_ARTISTS";
export const IS_ALLOWED_ARTIST = "IS_ALLOWED_ARTIST";
export const IS_ALLOWED_RETURNED = "IS_ALLOWED_RETURNED";

export const CHECK_ROLES = "CHECK_ROLES";
export const CHECK_ROLES_RETURNED = "CHECK_ROLES_RETURNED";
export const SWITCH_VS_COIN = "SWITCH_VS_COIN";
export const SWITCH_VS_COIN_RETURNED = "SWITCH_VS_COIN_RETURNED";

export const PING_COINGECKO = "PING_COINGECKO";
export const PING_COINGECKO_RETURNED = "PING_COINGECKO_RETURNED";
export const GET_COIN_LIST = "GET_COIN_LIST";
export const COINLIST_RETURNED = "COINLIST_RETURNED";
export const GET_COIN_DATA = "GET_COIN_DATA";
export const COIN_DATA_RETURNED = "COIN_DATA_RETURNED";
export const GET_COIN_PRICECHART = "GET_COIN_PRICECHART";
export const GETTING_NEW_CHART_DATA = "GETTING_NEW_CHART_DATA";
export const COIN_PRICECHART_RETURNED = "COIN_PRICECHART_RETURNED";
export const COINGECKO_POPULATE_FAVLIST = "COINGECKO_POPULATE_FAVLIST";
export const COINGECKO_POPULATE_FAVLIST_RETURNED =
  "COINGECKO_POPULATE_FAVLIST_RETURNED";
export const COINGECKO_POPULATE_TXLIST = "COINGECKO_POPULATE_TXLIST";
export const COINGECKO_POPULATE_TXLIST_RETURNED =
  "COINGECKO_POPULATE_TXLIST_RETURNED";
export const COINGECKO_GET_ALLTIME_CHART = "COINGECKO_GET_ALLTIME_CHART";
export const COINGECKO_ALLTIME_CHART_RETURNED =
  "COINGECKO_ALLTIME_CHART_RETURNED";
export const GECKO_GET_COINS = "GECKO_GET_COINS";
export const GECKO_GET_COINS_RETURNED = "GECKO_GET_COINS_RETURNED";
export const GECKO_GET_SPARKLINE_FROM_CONTRACT =
  "GECKO_GET_SPARKLINE_FROM_CONTRACT";
export const GECKO_GET_SPARKLINE_FROM_CONTRACT_RETURNED =
  "GECKO_GET_SPARKLINE_FROM_CONTRACT_RETURNED";

export const UNISWAP_TRADE = "UNISWAP_TRADE";
export const GET_CONTRACT_ABI = "GET_CONTRACT_ABI";

export const PIE_CHART_SELECTED = "PIE_CHART_SELECTED";

export const DB_GET_USER_GAMESTATS = "DB_GET_USER_GAMESTATS";
export const DB_GET_USER_GAMESTATS_RETURNED = "DB_GET_USER_GAMESTATS_RETURNED";
export const DB_GET_ALL_LS = "DB_GET_ALL_LS";
export const DB_GET_ALL_LS_RETURNED = "DB_GET_ALL_LS_RETURNED";
export const DB_GET_TOKEN_LS = "DB_GET_TOKEN_LS";
export const DB_GET_TOKEN_LS_RETURNED = "DB_GET_TOKEN_LS_RETURNED";
export const DB_GET_USER_TOKEN_LS = "DB_GET_USER_TOKEN_LS";
export const DB_GET_USER_TOKEN_LS_RETURNED = "DB_GET_USER_TOKEN_LS_RETURNED";
export const DB_GET_USER_LS = "DB_GET_USER_LS";
export const DB_GET_USER_LS_RETURNED = "DB_GET_USER_LS_RETURNED";
export const DB_CREATE_LS = "DB_CREATE_LS";
export const DB_CREATE_LS_RETURNED = "DB_CREATE_LS_RETURNED";
export const DB_CHECK_LS_RESULT = "DB_CHECK_LS_RESULT";
export const DB_CHECK_LS_RESULT_RETURNED = "DB_CHECK_LS_RESULT_RETURNED";

export const DB_NEW_NICKNAME = "DB_NEW_NICKNAME";
export const DB_NEW_NICKNAME_RETURNED = "DB_NEW_NICKNAME_RETURNED";
export const DB_NEW_AVATAR = "DB_NEW_AVATAR";
export const DB_NEW_AVATAR_RETURNED = "DB_NEW_AVATAR_RETURNED";
export const DB_GET_LEADERBOARD = "DB_GET_LEADERBOARD";
export const DB_GET_LEADERBOARD_MINIGAME = "DB_GET_LEADERBOARD_MINIGAME";
export const DB_GET_LEADERBOARD_RETURNED = "DB_GET_LEADERBOARD_RETURNED";

export const DB_GET_PORTFOLIO = "DB_GET_PORTFOLIO";
export const DB_GET_PORTFOLIO_RETURNED = "DB_GET_PORTFOLIO_RETURNED";
export const DB_GET_PORTFOLIO_MULTICHAIN = "DB_GET_PORTFOLIO_MULTICHAIN";
export const DB_GET_PORTFOLIO_MULTICHAIN_RETURNED =
  "DB_GET_PORTFOLIO_MULTICHAIN_RETURNED";

export const DB_GET_PORTFOLIO_POSITIONS = "DB_GET_PORTFOLIO_POSITIONS";
export const DB_GET_PORTFOLIO_POSITIONS_RETURNED =
  "DB_GET_PORTFOLIO_POSITIONS_RETURNED";

export const DB_GET_NFTS = "DB_GET_NFTS";
export const DB_GET_NFTS_RETURNED = "DB_GET_NFTS_RETURNED";
export const DB_GET_NFTS_VALUE = "DB_GET_NFTS_VALUE";
export const DB_GET_NFTS_VALUE_RETURNED = "DB_GET_NFTS_VALUE_RETURNED";

export const DB_GET_PORTFOLIO_STATS = "DB_GET_PORTFOLIO_STATS";
export const DB_GET_PORTFOLIO_STATS_RETURNED =
  "DB_GET_PORTFOLIO_STATS_RETURNED";
export const DB_GET_PORTFOLIO_ASSET_STATS = "DB_GET_PORTFOLIO_ASSET_STATS";
export const DB_GET_PORTFOLIO_ASSET_STATS_RETURNED =
  "DB_GET_PORTFOLIO_ASSET_STATS_RETURNED";
export const DB_GET_PORTFOLIO_CHART = "DB_GET_PORTFOLIO_CHART";
export const DB_GET_PORTFOLIO_CHART_RETURNED =
  "DB_GET_PORTFOLIO_CHART_RETURNED";
export const DB_GET_ASSETSTATS = "DB_GET_ASSETSTATS";
export const DB_GET_ASSETSTATS_RETURNED = "DB_GET_ASSETSTATS_RETURNED";
export const DB_UPDATE_PORTFOLIO = "DB_UPDATE_PORTFOLIO";
export const DB_UPDATE_PORTFOLIO_RETURNED = "DB_UPDATE_PORTFOLIO_RETURNED";
export const DB_SET_USER_WALLET_NICKNAME = "DB_SET_USER_WALLET_NICKNAME";
export const DB_GET_USER_WALLET_NICKNAME = "DB_GET_USER_WALLET_NICKNAME";
export const DB_SET_USER_WALLET_NICKNAME_RETURNED =
  "DB_SET_USER_WALLET_NICKNAME_RETURNED";
export const DB_GET_USER_WALLET_NICKNAME_RETURNED =
  "DB_GET_USER_WALLET_NICKNAME_RETURNED";
export const DB_REMOVE_USER_WALLET_NICKNAME = "DB_REMOVE_USER_WALLET_NICKNAME";
export const DB_REMOVE_USER_WALLET_NICKNAME_RETURNED =
  "DB_REMOVE_USER_WALLET_NICKNAME_RETURNED";

export const GET_TRANSACTION_RECEIPT = "GET_TRANSACTION_RECEIPT";
export const GET_TRANSACTION_RECEIPT_RETURNED =
  "GET_TRANSACTION_RECEIPT_RETURNED";

export const DB_GET_ADDRESS_TX = "DB_GET_ADDRESS_TX";
export const DB_GET_ADDRESS_TX_RETURNED = "DB_GET_ADDRESS_TX_RETURNED";

export const DB_GET_CRYPTONEWS = "DB_GET_CRYPTONEWS";
export const DB_GET_CRYPTONEWS_RETURNED = "DB_GET_CRYPTONEWS_RETURNED";

export const DB_GET_ASSET_FULLDATA = "DB_GET_ASSET_FULLDATA";
export const DB_GET_ASSET_FULLDATA_RETURNED = "DB_GET_ASSET_FULLDATA_RETURNED";

export const CHECK_BETA_ACCESS = "CHECK_BETA_ACCESS";
export const CHECK_BETA_ACCESS_RETURNED = "CHECK_BETA_ACCESS_RETURNED";
