export const CONNECTION_CONNECTED = "CONNECTION_CONNECTED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";

export const CHECK_ACCOUNT = "CHECK_ACCOUNT";
export const CHECK_ACCOUNT_RETURNED = "CHECK_ACCOUNT_RETURNED";

export const CONNECT_METAMASK = "CONNECT_METAMASK";
export const CONNECT_METAMASK_PASSIVE = "CONNECT_METAMASK_PASSIVE";
export const METAMASK_CONNECTED = "METAMASK_CONNECTED";
export const CONNECT_LEDGER = "CONNECT_LEDGER";

export const GET_CONTRACT_EVENTS = "GET_CONTRACT_EVENTS";
export const GET_CONTRACT_EVENTS_RETURNED = "GET_CONTRACT_EVENTS_RETURNED";

export const ERROR = "ERROR";

export const GET_CURRENTEDITION = "GET_CURRENTEDITION";
export const EDITION_RETURNED = "EDITION_RETURNED";
export const GET_USER_EDITIONS = "GET_USER_EDITIONS";
export const USER_EDITIONS_RETURNED = "USER_EDITIONS_RETURNED";
export const GET_USER_EDITIONS_DETAILS = "GET_USER_EDITIONS_DETAILS";
export const GET_ARTIST_EDITIONS = "GET_ARTIST_EDITIONS";
export const ARTIST_EDITIONS_RETURNED = "ARTIST_EDITIONS_RETURNED";
export const GET_ARTIST_EDITIONS_DETAILS = "GET_ARTIST_EDITIONS_DETAILS";
export const ARTIST_EDITIONS_DETAILS_RETURNED =
  "ARTIST_EDITIONS_DETAILS_RETURNED";
export const GET_EDITION_DETAILS = "GET_EDITION_DETAILS";
export const GET_EDITIONS_DETAILS = "GET_EDITIONS_DETAILS";
export const EDITION_DETAILS_RETURNED = "EDITION_DETAILS_RETURNED";
export const EDITIONS_DETAILS_RETURNED = "EDITION_DETAILS_RETURNED";

export const GET_TOKENJSON = "GET_TOKENJSON";
export const TOKENJSON_RETURNED = "TOKENJSON_RETURNED";

export const BUY_EDITION = "BUY_EDITION";
export const BUY_RETURNED = "BUY_RETURNED";
export const CREATE_NEW_EDITION = "CREATE_NEW_EDITION";
export const NEW_EDITION_RETURNED = "NEW_EDITION_RETURNED";

export const GET_AVAILABLE_ITEMS = "GET_AVAILABLE_ITEMS";
export const GET_ITEMS_CIRCULATING = "GET_ITEMS_CIRCULATING";
export const GET_SALES_VALUE = "GET_SALES_VALUE";
export const GET_ACCOUNT_ROLES = "GET_ACCOUNT_ROLES";
export const AVAILABLE_ITEMS_RETURNED = "AVAILABLE_ITEMS_RETURNED";
export const ITEMS_CIRCULATING_RETURNED = "ITEMS_CIRCULATING_RETURNED";
export const SALES_VALUE_RETURNED = "SALES_VALUE_RETURNED";

export const ACCOUNT_ROLES_RETURNED = "ACCOUNT_ROLES_RETURNED";
export const SET_ROLES = "SET_ROLES";
export const REVOKE_ROLES = "REVOKE_ROLES";

export const CHECK_ROLES = "CHECK_ROLES";
export const CHECK_ROLES_RETURNED = "CHECK_ROLES_RETURNED";
