export const GET_PROTOCOL_NAMES = "GET_PROTOCOL_NAMES";
export const GET_TOKENADAPTER_NAMES = "GET_PROTOCOL_NAMES";
export const GET_PROTOCOL_BALANCE = "GET_PROTOCOL_BALANCE";
export const GET_PROTOCOLS_BALANCES = "GET_PROTOCOLS_BALANCES";
export const GET_TOKEN_COMPONENTS = "GET_TOKEN_COMPONENTS";
export const GET_CONTRACT_ABI = "GET_CONTRACT_ABI";
