export const ERROR_ZERION = "ERROR_ZERION";
export const ZERION_GET_ADDRESS_CHART = "ZERION_GET_ADDRESS_CHART";
export const ZERION_ADDRESS_CHART_RETURNED = "ZERION_ADDRESS_CHART_RETURNED";
export const ZERION_GET_ADDRESS_PORTFOLIO = "ZERION_GET_ADDRESS_PORTFOLIO";
export const ZERION_ADDRESS_PORTFOLIO_RETURNED =
  "ZERION_ADDRESS_PORTFOLIO_RETURNED";
export const ZERION_GET_ASSETSTATS = "ZERION_GET_ASSETSTATS";
export const ZERION_ASSETSTATS_RETURNED = "ZERION_ASSETSTATS_RETURNED";
